name: star_wars_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  go_router: ^13.2.4
  intl: ^0.19.0
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
        weight: 900
      - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
      - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
        weight: 600
  - family: StarWars
    fonts:
      - asset: assets/fonts/star_wars/Starjedi.ttf
      - asset: assets/fonts/star_wars/Starjhol.ttf
  - family: Roboto
    fonts:
      - asset: assets/fonts/roboto/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/roboto/Roboto-Light.ttf
        weight: 200
      - asset: assets/fonts/roboto/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/roboto/Roboto-Regular.ttf