name: star_wars_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  bloc: ^9.0.0
  countup: ^0.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  floor: ^1.4.2
  floor_generator: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_lints: ^5.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  http: ^1.2.0
  intl: ^0.20.2
  mime: ^2.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  retrofit: ^4.1.0
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  retrofit_generator: ^9.1.9
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_image.jpg
    - assets/images/default_vehicle_image.png
    - assets/images/space_background.jpg
  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
        weight: 900
      - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
      - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
        weight: 600
  - family: StarWars
    fonts:
      - asset: assets/fonts/star_wars/Starjedi.ttf
      - asset: assets/fonts/star_wars/Starjhol.ttf
  - family: Roboto
    fonts:
      - asset: assets/fonts/roboto/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/roboto/Roboto-Light.ttf
        weight: 200
      - asset: assets/fonts/roboto/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/roboto/Roboto-Regular.ttf