name: CI
on:
    pull_request:
        branches:
            - main
jobs:
    flutter_test:
        name: Run flutter analyze and test
        runs-on: ubuntu-latest
        steps:
            - name: Check Out
              uses: actions/checkout@v2
            - name: Setup Java
              uses: actions/setup-java@v1
              with:
                java-version: "12.x"
            # allows to use flutter commands in this workflow
            - name: Setup Flutter Commands
              uses: subosito/flutter-action@v1
              with:
                channel: "stable"
            - run: flutter pub get
            - run: flutter analyze
            - run: flutter test